### ISSUE TITLE
Wrong second screen shadow position on Win10

### ISSUE THREAD

**Issue by dayfixer** [antonypro/QGoodWindow#32]
Hello, I encountered such a problem:
![screen](https://user-images.githubusercontent.com/19245959/227756542-01a8e8a3-3d52-405c-ac1c-263021218723.gif)

This happens on the second screen.

-----------

Primary screen dpi: 125% (1080p)
Second screen dpi: 125% (4k)
QMainwindow version: Current master branch 
Windows OS: Windows 10 Home, 22H2, 19045.2728
Test on
- Qt5.12.12, Mingw: 11.2.0, 64bit
- Qt5.12.12, VS2022, 17.5.33502.453, 64bit
- Q5.15.2, VS2022, 17.5.33502.453, 64bit

All have this problem.

**Comment by antonypro** [comment]
@dayfixer: Hi!

This problem is caused by mix of metrics that considers the pixel ratio and others that don't.

I'm working to solve this problem and make `QGoodWindow` behaves as expected.

Thanks for reporting.

**Comment by antonypro** [comment]
@dayfixer: This bug was solved on version 2.4.

**Comment by dayfixer** [comment]
Thanks! 
But it seems there is still a problem on qt5...

![screen](https://github.com/antonypro/QGoodWindow/assets/19245959/1dbceadd-fc26-47bc-9e82-23a5042ab894)

**Comment by antonypro** [comment]
@dayfixer: Thanks for report, I'm working to solve this problem and I will reopen the issue.

**Comment by antonypro** [comment]
@dayfixer: Could you please try version 2.4.1?

**Comment by dayfixer** [comment]
@antonypro 

I'm sorry, but I found out it's still the same as last time, and I'll see what the reason is when I have time.

Thanks for your update!

BTW，Version 2.4 is fine on QT6, not on QT5, but 2.4.1 is not both on Qt6 and Qt5

![image](https://github.com/antonypro/QGoodWindow/assets/19245959/689855d6-e542-4363-aab1-4b2fe6812cf0)

**Comment by antonypro** [comment]
@dayfixer: Hi! I think that i solved the problem, however I'm asking you to test what may be the 2.4.2 version:

**EDIT** the link was changed:
https://github.com/antonypro/QGoodWindow/tree/test/QGoodWindow-test1

The problem:

I've tested `QGoodWindow` on Windows 10 with two screens and moved the toolbar to the top, i noticed that causes problems in `QGoodWindow` when it's moved to the secondary screen, then i realized that i made a mistake in detect the current screen, instead of consider the whole screen, I'm considering only the work area, this is wrong because may cause, for example, the primary monitor to not have position 0x,0y if the toolbar is on top or left, and `QScreen` returns `nullptr`.

I'm waiting your feedback.
Thanks!

**Comment by dayfixer** [comment]
@antonypro 

Thank you, I will test it as soon as possible!

**Comment by dayfixer** [comment]
@antonypro 

Hi! I have test `test1` and `test2`:

test1: not works both on Qt5 and Qt6, and something weird while dragging the widget to second screen(only Qt6):
(Use `Win+D` to minimize the widget, then maximize the widget from taskbar, it will become normal)
![screen2](https://github.com/antonypro/QGoodWindow/assets/19245959/5fe35bd0-e960-4188-90ab-85c1e07fee1f)

test2: only works on Qt6, but QMessageBox has white margin: 

![image](https://github.com/antonypro/QGoodWindow/assets/19245959/e2fa6117-28f6-4d2e-a66c-2b151161b6f5)

**Comment by antonypro** [comment]
@dayfixer: I released a new version called `test3`, this have many changes on multi monitor with different DPI support.

Could you please test it?

https://github.com/antonypro/QGoodWindow/tree/test/QGoodWindow-test3

And don't worry about reporting new problems!

Thanks!

**Comment by dayfixer** [comment]
@antonypro 

Hi! I have test `test3`:

not works on Qt5, works well on Qt6 (QMessageBox works well too)!

This is a new problem on Qt5: It turns white after dragging to the second screen

![screen3](https://github.com/antonypro/QGoodWindow/assets/19245959/42db740b-1fd4-49de-87fc-aa079070bbed)

**Comment by antonypro** [comment]
@dayfixer: Hi! I released version 2.4.2 beta 1 and it adds more improvements to multi monitor support.

It should works on both Qt 5 and Qt 6.

You can test it in the following link:

https://github.com/antonypro/QGoodWindow/tree/test/QGoodWindow-2.4.2-beta1

Thanks!

**Comment by dayfixer** [comment]
@antonypro 

Hi! I have test 2.4.2 beta 1, they both works on Qt5 and Qt6, thanks a lot!

**Comment by antonypro** [comment]
I will close this issue as it seems to be solved!
