### ISSUE TITLE
window move issue on Mac OS

### ISSUE THREAD

**Issue by flyleier** [antonypro/QGoodWindow#43]
- OS: M1 MacOS 13.4.1
- Qt: 5.15.2, 6.4.2, 6.5.2
- description:
   When dragging the frameless window upwards, after touching with the system menu bar, the frameless window will not be able to move, and at the same time, the maximize button, minimize button and close button of the frameless window will not work, but customized buttons work.

https://github.com/antonypro/QGoodWindow/assets/19969426/eeabd545-cf8d-40a0-8fd2-4ceb9bc60143

**Comment by antonypro** [comment]
@flyleier: I released version 2.4.2 beta 1 on the test branch, it should fix the problem reported:

https://github.com/antonypro/QGoodWindow/tree/test/QGoodWindow-2.4.2-beta1

It replaces `frameGeometry()` with native code on `ncHitTest()` and it should fix the problem.

https://github.com/antonypro/QGoodWindow/blob/0ba0f3207b411fe288806c5be2644a9fc3713399/QGoodWindow-2.4.2-beta1/QGoodWindow/src/qgoodwindow.cpp#L4252-L4260

Could you please test it?

Thanks!

**Comment by flyleier** [comment]
@antonypro Sorry for late reply. I just tested the 2.4.2-beta1 version, the window can be moved, but the buttons(maximize, minimize and close ) still don't work when window touch the system menu bar.

**Comment by antonypro** [comment]
Hi, @flyleier!

For what I could test, when the buttons are not working that's no `mouseMove` event, however after moving the window the caption buttons functionality are restored. I think that's enough for now. 

What i have to say is that I'm not going to workaround this problem for now, maybe a deep analysis and a fix in a future version, but not for version 2.4.2.

Thanks!

**Comment by antonypro** [comment]
Hi, @flyleier!

I'm reviewing my decision and I will include a fix for this problem in version 2.4.2.

Also, I've added a possibility to use native caption buttons on macOS, which is now the default.

You can see the progress here: https://github.com/antonypro/QGoodWindow/tree/test/QGoodWindow-2.4.2-beta2

Thanks!

**Comment by antonypro** [comment]
Hi, @flyleier! The problem seems to be solved on version 2.4.2. So I will close this issue.
